### PR TITLE
add irc_default event for unhandled irc responses

### PR DESCRIPTION
**Pull request by Grinnz**
irc_default event that is emitted for any irc response that is not handled in some other way, useful for debugging various irc responses.

### CODE REVIEW

**Comment by jhthorsen** [comment]
Why can't you just use MOJO_IRC_DEBUG=1 when debugging?

**Comment by Grinnz** [comment]
I didn't know about the debug flag, that is useful. But the default handler is more useful for long-term debugging as it will only handle "unexpected" messages.

**Comment by jhthorsen** [comment]
I will let @marcusramberg decide. I'm not convinced, but I'm also not against it.

**Comment by jhthorsen** [comment]
I've discussed this with @marcusramberg and we decided to reject this PR.

**Pull request closed without merging**
